### ISSUE TITLE
Is it possible to create PBIT file through Github actions workflow 

### ISSUE THREAD

**Issue by NitinSapre** [pbi-tools/pbi-tools#256]
Is it possible to create PBIT file through Github actions workflow.
I have stored all the template extracted files into my github repository like you did [https://github.com/pbi-tools/adventureworksdw2020-pbix/tree/main/pbix](here).

I tried something like this - 

```
name: test pbi-tools compile

on:
  push:
    branches: [ test-pbi-tools ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: powerbi
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      - uses: actions/checkout@v3

      - name: pbi-tools compile
        run: /app/pbi-tools/pbi-tools.core compile .\Template\Files -format PBIT -outpath test.pbit
```

But it didn't work. The compile step just didn't do anything and build was stuck there.

Any pointers?
